# Validate changes to this class with: curl -X POST --data-binary @.codecov.yml https://codecov.io/validate

codecov:
  branch: dev

coverage:
  precision: 2
  round: down
  range: "25...75"

  status:
    project:
      default: false  # disable the default status that measures entire project
      SalesforceAnalytics:
        target: auto
        paths: 
          - "libs/SalesforceAnalytics/SalesforceAnalytics/"
        flags: 
          - SalesforceAnalytics
      SalesforceSDKCommon:
        target: auto
        paths: 
          - "libs/SalesforceSDKCore/SalesforceSDKCommon/"
        flags: 
          - SalesforceSDKCommon
      SalesforceSDKCore:
        target: auto
        paths: 
          - "libs/SalesforceSDKCore/SalesforceSDKCore/"
        flags: 
          - SalesforceSDKCore
      SmartStore:
        target: auto
        paths: 
          - "libs/SmartStore/SmartStore/"
        flags: 
          - SmartStore
      MobileSync:
        target: auto
        paths: 
          - "libs/MobileSync/MobileSync/"
        flags: 
          - MobileSync

ignore:
  - "shared"
  - "native"
  - "libs/**/*Test*/*"

flag_management:
  default_rules: # the rules that will be followed for any flag added, generally
    carryforward: true

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false